# Project requires MacOS to build - run pytest pre-commit

name: Codecov

on:
  push:
  pull_request:

jobs:
  codecov:
    runs-on: macos-26

    steps:
      - uses: actions/checkout@v4
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
